ALTER TYPE "Gender" ADD VALUE IF NOT EXISTS 'SELF_DESCRIBE';
ALTER TYPE "Gender" ADD VALUE IF NOT EXISTS 'PREFER_NOT_TO_SAY';

ALTER TYPE "RelationshipGoal" ADD VALUE IF NOT EXISTS 'LONG_TERM';
ALTER TYPE "RelationshipGoal" ADD VALUE IF NOT EXISTS 'SERIOUS_OPEN_TO_SHORT_TERM';
